# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='final',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='test1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='test2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='test3',
            field=models.IntegerField(default=0),
        ),
    ]
