# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_auto_20171016_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='test1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='test2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='test3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
